# Generated by Django 4.1.2 on 2022-11-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchases_quantity_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='Ingredient',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem', verbose_name='menu items'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem', verbose_name='menu items'),
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient', verbose_name='ingredients'),
        ),
    ]
